const users = [
  {
    id: 1,
    name: "John Doe",
    email: "john@example.com",
    password: "123890",
    phone: "1234567890",
    role: "user",
    status: "active",
  },
  {
    id: 2,
    name: "Dude Smith",
    email: "Dude@example.com",
    phone: "9876543210",
    role: "admin",
    status: "inactive",
  },
  {
    id: 3,
    name: "Jane Smith",
    email: "jane@example.com",
    password: "123890",
    phone: "9876543210",
    role: "admin",
    status: "inactive",
  },
  {
    id: 4,
    name: "Mary Smith",
    email: "Mary@example.com",
    password: "123890",
    phone: "9876543210",
    role: "admin",
    status: "inactive",
  },
  {
    id: 5,
    name: "Jane Doe",
    email: "Jane@example.com",
    password: "123890",
    phone: "9876543210",
    role: "admin",
    status: "active",
  },
];
export default users;
